
service: serverless-demo-app

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2

  iamRoleStatements:
    - Effect: "Allow"
      Action:
          - "sqs:DeleteMessage"
          - "sqs:GetQueueUrl"
          - "sqs:ReceiveMessage"
          - "sqs:SendMessage"
          - "sqs:GetQueueAttributes"
      Resource:
        Fn::GetAtt:
          - productPromotionProcessQueue
          - Arn

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: 
        Fn::Join:
          - ":"
          - - arn:aws:dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - table/productPromotionTable*

package:
  individually: true
  exclude:
    - "**/*"  # quotes(") are needed

functions:
  productSalesAnalysis:
    handler: product-sales-analysis/index.handler
    description: Product Sales Analysis
    memorySize: 128
    events:
      - schedule: 
          rate: cron(0 22 * * ? *)
          enabled: true
    environment:
      PRODUCT_PROMOTION_QUEUE_NAME:
        Fn::GetAtt:
          - productPromotionProcessQueue
          - QueueName
    package:
      include:
        - product-sales-analysis/**
      exclude:
        - product-sales-analysis/node_modules/aws-sdk/**

  productPromotion:
    handler: product-promotion/index.handler
    description: Product Promotion
    memorySize: 128
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - productPromotionProcessQueue
              - Arn
        batchSize: 10
    environment:
      PRODUCT_PROMOTION_TABLE_NAME:
        Ref: productPromotionTable
    package:
      include:
        - product-promotion/**
      exclude:
        - product-promotion/node_modules/aws-sdk/**

  getProductPromotionAPI:
    handler: product-promotion-api/index.handler
    description: Get Product Promition API
    memorySize: 128
    events:
      - http:
          path: product-promotion
          method: get
    environment:
      PRODUCT_PROMOTION_TABLE_NAME:
        Ref: productPromotionTable
    package:
      include:
        - product-promotion-api/**
      exclude:
        - product-promotion-api/node_modules/aws-sdk/** 

resources:
  Resources:
    productPromotionProcessQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:service}-product-promotion-queue-${self:provider.stage}
        VisibilityTimeout: 300

    productPromotionTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: productPromotionTable
        AttributeDefinitions:
          - AttributeName: promotionCode
            AttributeType: S
        KeySchema:
          - AttributeName: promotionCode
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
